'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://Intertech.com", ConfigurationName:="ServiceReference1.IEightBall")>  _
    Public Interface IEightBall
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://Intertech.com/IEightBall/ObtainAnswerToQuestion", ReplyAction:="http://Intertech.com/IEightBall/ObtainAnswerToQuestionResponse")>  _
        Function ObtainAnswerToQuestion(ByVal userQuestion As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IEightBallChannel
        Inherits ServiceReference1.IEightBall, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class EightBallClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IEightBall)
        Implements ServiceReference1.IEightBall
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtainAnswerToQuestion(ByVal userQuestion As String) As String Implements ServiceReference1.IEightBall.ObtainAnswerToQuestion
            Return MyBase.Channel.ObtainAnswerToQuestion(userQuestion)
        End Function
    End Class
End Namespace
